fix: handle settings with missing `shared` section
This allows configuration files without a `shared` field, using the
default value if missing.

Before:

    $ pueued -vv -c /dev/null
    Error: Error while reading configuration.

    Caused by:
        Error while reading configuration:
        missing field `shared`

After:

    $ pueued -vv -c /dev/null
    21:12:26 [INFO] Restoring state
    21:12:26 [INFO] Using unix socket at: "/run/user/1000/pueue_rycee.socket"